import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {auth,db,ref,get,set,update,push,onValue,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,googleProvider} from './firebase';
import './styles.css';

const demoUsers=[
 {uid:'demo-1',username:'skywalker',nickname:'Sky Walker',bio:'Building above the noise.',region:'IN',verified:true,followers:1248,following:310,posts:42,avatar:'avatar.png'},
 {uid:'demo-2',username:'nova',nickname:'Nova Ray',bio:'Night skies & bright ideas.',region:'US',verified:true,followers:982,following:214,posts:31,avatar:'icon.png'},
 {uid:'demo-3',username:'pixelwave',nickname:'Pixel Wave',bio:'Visual storyteller.',region:'GB',verified:false,followers:712,following:189,posts:27,avatar:'avatar.png'}
];
const demoPosts=[
 {key:'p1',uid:'demo-1',username:'skywalker',nickname:'Sky Walker',avatar:'avatar.png',description:'Welcome to Skyline. Share your world, discover your people, and stay above the noise. ✨',publish_date:Date.now()-3600000,likes:128,comments:18,region:'IN',tags:'#skyline #community'},
 {key:'p2',uid:'demo-2',username:'nova',nickname:'Nova Ray',avatar:'icon.png',description:'Golden hour never misses. What are you exploring today?',publish_date:Date.now()-7200000,likes:84,comments:9,region:'US',tags:'#travel #sunset'},
 {key:'p3',uid:'demo-3',username:'pixelwave',nickname:'Pixel Wave',avatar:'avatar.png',description:'A quiet frame from a loud city.',publish_date:Date.now()-86400000,likes:241,comments:32,region:'GB',tags:'#photography'}
];
const demoStories=[{id:'s1',username:'skywalker',avatar:'avatar.png',label:'Your story'},{id:'s2',username:'nova',avatar:'icon.png',label:'Nova'},{id:'s3',username:'pixelwave',avatar:'avatar.png',label:'Pixel Wave'}];

function Icon({name,size=21,fill='none'}){const p={width:size,height:size,viewBox:'0 0 24 24',fill,stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round',strokeLinejoin:'round'}; const paths={home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,heart:<path d="M20.8 8.8c0 5.4-8.8 10.2-8.8 10.2S3.2 14.2 3.2 8.8A4.8 4.8 0 0 1 12 6.1a4.8 4.8 0 0 1 8.8 2.7Z"/>,message:<><path d="M20 11.5a7.5 7.5 0 0 1-7.5 7.5H7l-4 2 1.4-4.1A7.5 7.5 0 1 1 20 11.5Z"/></>,user:<><circle cx="12" cy="8" r="3.5"/><path d="M4.5 20c.8-4 3.3-6 7.5-6s6.7 2 7.5 6"/></>,bell:<><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,bookmark:<path d="M6 4.5A2.5 2.5 0 0 1 8.5 2h7A2.5 2.5 0 0 1 18 4.5V21l-6-3.5L6 21Z"/>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,send:<><path d="m21 3-7.4 18-3.5-7.1L3 10.4Z"/><path d="M21 3 10.1 13.9"/></>,settings:<><path d="M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z"/><path d="m19.4 15 .1.1a2 2 0 0 1-2.8 2.8l-.1-.1a2 2 0 0 0-3.4 1.4v.2a2 2 0 0 1-4 0v-.2a2 2 0 0 0-3.4-1.4l-.1.1A2 2 0 1 1 3 15.1l.1-.1a2 2 0 0 0-1.4-3.4h-.2a2 2 0 0 1 0-4h.2A2 2 0 0 0 3.1 4.2L3 4.1A2 2 0 0 1 5.8 1.3l.1.1a2 2 0 0 0 3.4-1.4v-.2a2 2 0 0 1 4 0V0a2 2 0 0 0 3.4 1.4l.1-.1A2 2 0 0 1 19.6 4l-.1.1A2 2 0 0 0 20.9 7.5h.2a2 2 0 0 1 0 4h-.2a2 2 0 0 0-1.5 3.5Z" transform="scale(.9) translate(1.3 1.3)"/></>,x:<><path d="m6 6 12 12M18 6 6 18"/></>,play:<><path d="m9 6 10 6-10 6Z"/></>,camera:<><path d="M4 7h3l1.5-2h7L17 7h3v12H4Z"/><circle cx="12" cy="13" r="3.5"/></>};return <svg {...p}>{paths[name]}</svg>}

function Avatar({src='avatar.png',size=44,ring=false}){return <div className={'avatar '+(ring?'story-ring':'')} style={{width:size,height:size}}><img src={'/assets/'+src} onError={e=>e.currentTarget.style.display='none'}/><span>{src==='icon.png'?'N':'S'}</span></div>}
function Shell({page,setPage,user,onLogout,children}){const nav=[['home','Home'],['explore','Explore'],['lines','Lines'],['messages','Messages'],['profile','Profile']];return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><span>Skyline</span></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon name={id==='explore'?'search':id==='lines'?'play':id==='messages'?'message':id==='profile'?'user':'home'}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button onClick={()=>setPage('notifications')}><Icon name="bell"/><span>Notifications</span></button><button onClick={()=>setPage('settings')}><Icon name="settings"/><span>Settings</span></button><button className="mini-user" onClick={()=>setPage('profile')}><Avatar size={36}/><span>@{user?.username||'skywalker'}</span></button></div></aside><main className="main"><header className="topbar"><div className="mobile-brand">Skyline</div><div className="top-actions"><button onClick={()=>setPage('explore')}><Icon name="search"/></button><button onClick={()=>setPage('notifications')} className="notify"><Icon name="bell"/><i/></button></div></header>{children}</main><div className="mobile-nav">{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><Icon name={id==='explore'?'search':id==='lines'?'play':id==='messages'?'message':id==='profile'?'user':'home'}/><span>{label}</span></button>)}</div></div>}

function Auth({onAuth}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function submit(e){e.preventDefault();setBusy(true);setErr('');try{let c;if(mode==='login')c=await signInWithEmailAndPassword(auth,email,password);else c=await createUserWithEmailAndPassword(auth,email,password);if(mode==='register'&&c.user)await set(ref(db,'skyline/users/'+c.user.uid),{uid:c.user.uid,username:username||email.split('@')[0],nickname:username||'Skyline User',bio:'',user_region:'',followers:0,following:0,posts:0});onAuth(c.user)}catch(x){setErr(x.message||'Unable to authenticate. Try demo mode.');setBusy(false)}}return <div className="auth"><div className="auth-card"><div className="auth-logo"><span>S</span></div><h1>{mode==='login'?'Welcome back':'Join Skyline'}</h1><p>{mode==='login'?'Log in to your community.':'Create your Skyline account.'}</p>{err&&<div className="error">{err}</div>}<form onSubmit={submit}>{mode==='register'&&<input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Continue':'Create account'}</button></form><button className="google" onClick={async()=>{try{const r=await signInWithPopup(auth,googleProvider);onAuth(r.user)}catch(e){setErr(e.message)}}}><b>G</b> Continue with Google</button><button className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?"Don't have an account? Create one":"Already have an account? Log in"}</button><button className="demo" onClick={()=>onAuth({uid:'demo-1',email:'demo@skyline.app',displayName:'Sky Walker'})}>Enter demo mode</button></div></div>}

function Stories({onOpen}){return <section className="stories"><div className="section-head"><h3>Stories</h3><button onClick={()=>onOpen('create-story')}>Add story</button></div><div className="story-row">{demoStories.map((s,i)=><button className="story" key={s.id} onClick={()=>onOpen('story',s)}><Avatar src={s.avatar} size={66} ring/><span>{s.label}</span></button>)}</div></section>}
function PostCard({post,onLike,onSave,onComment}){const [liked,setLiked]=useState(false),[saved,setSaved]=useState(false);return <article className="post"><div className="post-head"><div className="post-user"><Avatar src={post.avatar} size={44}/><div><b>@{post.username}{post.verified&&<em>✓</em>}</b><span>{timeAgo(post.publish_date)} · {post.region||'Global'}</span></div></div><button><Icon name="more"/></button></div><p className="post-text">{post.description}</p>{post.tags&&<div className="tags">{post.tags}</div>}<div className="post-media"><div className="media-glow"><span>SKYLINE</span><small>Share your view</small></div></div><div className="post-actions"><button className={liked?'liked':''} onClick={()=>{setLiked(!liked);onLike?.(post)}}><Icon name="heart" fill={liked?'currentColor':'none'}/><span>{post.likes+(liked?1:0)}</span></button><button onClick={()=>onComment?.(post)}><Icon name="message"/><span>{post.comments}</span></button><button onClick={()=>setSaved(!saved)} className={saved?'saved':''}><Icon name="bookmark" fill={saved?'currentColor':'none'}/></button><button className="share" onClick={()=>navigator.clipboard?.writeText(location.href)}><Icon name="send"/></button></div></article>}
function Home({setPage}){const [posts,setPosts]=useState(demoPosts),[tab,setTab]=useState('For You'),[composer,setComposer]=useState(false);useEffect(()=>{try{return onValue(ref(db,'skyline/posts'),s=>{if(s.exists()){const v=Object.entries(s.val()).map(([key,x])=>({key,...x})).sort((a,b)=>(b.publish_date||0)-(a.publish_date||0));if(v.length)setPosts(v)}})}catch{}},[]);function publish(text){const p={key:'local-'+Date.now(),uid:'demo-1',username:'skywalker',nickname:'Sky Walker',avatar:'avatar.png',description:text,publish_date:Date.now(),likes:0,comments:0,region:'IN'};setPosts(x=>[p,...x]);setComposer(false);try{push(ref(db,'skyline/posts'),p)}catch{}}return <div className="page home"><div className="page-head"><div><p className="eyebrow">THURSDAY, AUGUST 27</p><h1>What’s new today?</h1></div><button className="create-btn" onClick={()=>setComposer(true)}><Icon name="plus"/> Create</button></div><Stories onOpen={()=>{}}/><div className="feed-tabs">{['For You','Following','Trending','Photos'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{composer&&<Composer onPublish={publish} onClose={()=>setComposer(false)}/>}<div className="feed">{posts.map(p=><PostCard key={p.key} post={p}/>)}</div></div>}
function Composer({onPublish,onClose}){const [text,setText]=useState('');return <div className="modal-back"><div className="modal"><div className="modal-head"><h2>Create post</h2><button onClick={onClose}><Icon name="x"/></button></div><div className="composer-user"><Avatar size={42}/><b>@skywalker</b></div><textarea autoFocus maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder="What's happening above the noise?"/><div className="composer-foot"><span>{text.length}/500</span><button className="primary" disabled={!text.trim()} onClick={()=>onPublish(text.trim())}>Publish</button></div></div></div>}
function Explore(){const [q,setQ]=useState('');const users=demoUsers.filter(u=>(u.username+u.nickname+u.bio).toLowerCase().includes(q.toLowerCase()));return <div className="page"><div className="page-head"><div><p className="eyebrow">DISCOVER</p><h1>Explore</h1></div></div><div className="searchbox"><Icon name="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, posts, topics"/></div><div className="explore-grid"><section><div className="section-head"><h3>Recommended users</h3></div>{users.map(u=><div className="user-row" key={u.uid}><Avatar src={u.avatar} size={52}/><div><b>@{u.username} {u.verified&&<em>✓</em>}</b><span>{u.nickname} · {u.followers} followers</span></div><button className="follow">Follow</button></div>)}</section><section className="trending"><div className="section-head"><h3>Trending topics</h3></div>{['#skyline','#photography','#travel','#design','#nightlife'].map((x,i)=><div className="trend" key={x}><span>0{i+1}</span><b>{x}</b><small>{(12-i*2)+'.'+i+'K posts'}</small></div>)}</section></div></div>}
function Lines(){return <div className="page lines-page"><div className="page-head"><div><p className="eyebrow">SHORT VIDEO</p><h1>Lines</h1></div><button className="create-btn"><Icon name="plus"/> Create Line</button></div><div className="lines-grid">{[1,2,3,4,5,6].map((x,i)=><div className="line-card" key={x}><div className="line-video"><span className="play"><Icon name="play"/></span><small>0:{18+i}</small></div><div className="line-info"><Avatar src={i%2?'icon.png':'avatar.png'} size={34}/><div><b>@{['nova','skywalker','pixelwave'][i%3]}</b><span>{['Original Sound','City Nights','Ocean Drive'][i%3]}</span></div><button><Icon name="heart"/></button></div></div>)}</div></div>}
function Messages({setPage}){const [active,setActive]=useState(null);const chats=[['nova','Nova Ray','That sunset is unreal.','2m','icon.png'],['pixelwave','Pixel Wave','Sent a photo','18m','avatar.png'],['skywalker','Sky Walker','See you on Skyline.','1h','avatar.png']];if(active)return <Chat name={active[1]} avatar={active[4]} back={()=>setActive(null)}/>;return <div className="page messages"><div className="page-head"><div><p className="eyebrow">PRIVATE</p><h1>Messages</h1></div><button className="icon-btn"><Icon name="plus"/></button></div><div className="message-search"><Icon name="search"/><input placeholder="Search conversations"/></div>{chats.map(c=><button className="chat-row" key={c[0]} onClick={()=>setActive(c)}><Avatar src={c[4]} size={52}/><div><b>@{c[0]}</b><span>{c[2]}</span></div><time>{c[3]}</time></button>)}</div>}
function Chat({name,avatar,back}){const [msgs,setMsgs]=useState([{me:false,t:'Hey! Welcome to Skyline 👋'},{me:true,t:'Thanks! This place feels great.'},{me:false,t:'That sunset is unreal.'}]),[text,setText]=useState('');return <div className="chat-page"><header><button onClick={back}><Icon name="x"/></button><Avatar src={avatar} size={40}/><div><b>{name}</b><span>online</span></div><button><Icon name="more"/></button></header><div className="chat-body">{msgs.map((m,i)=><div className={'bubble '+(m.me?'me':'')} key={i}>{m.t}<small>{i+1}m</small></div>)}</div><div className="chat-compose"><button><Icon name="camera"/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&text.trim()){setMsgs([...msgs,{me:true,t:text}]);setText('')}}} placeholder="Message…"/><button onClick={()=>{if(text.trim()){setMsgs([...msgs,{me:true,t:text}]);setText('')}}}><Icon name="send"/></button></div></div>}
function Profile({user}){const [tab,setTab]=useState('posts');return <div className="page profile-page"><div className="profile-cover"><div className="cover-sky"/></div><div className="profile-main"><Avatar size={92} ring/><div className="profile-title"><div><h1>Sky Walker <em>✓</em></h1><span>@skywalker</span></div><button className="edit">Edit profile</button></div><p>Building above the noise. Sharing moments, ideas and stories from the skyline.</p><div className="stats"><div><b>42</b><span>Posts</span></div><div><b>1.2K</b><span>Followers</span></div><div><b>310</b><span>Following</span></div></div><div className="profile-tabs"><button className={tab==='posts'?'active':''} onClick={()=>setTab('posts')}>Posts</button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>Saved</button><button className={tab==='media'?'active':''} onClick={()=>setTab('media')}>Media</button></div><div className="profile-grid">{[1,2,3,4,5,6].map(x=><div key={x} className="grid-tile"><span>SKYLINE</span></div>)}</div></div></div>}
function Notifications(){return <div className="page"><div className="page-head"><div><p className="eyebrow">ACTIVITY</p><h1>Notifications</h1></div></div><div className="notif-list">{[['nova','liked your post','2m','icon.png'],['pixelwave','started following you','18m','avatar.png'],['skywalker','replied to your comment','1h','avatar.png'],['nova','mentioned you in a post','3h','icon.png']].map((n,i)=><div className="notif" key={i}><Avatar src={n[3]} size={48}/><div><b>@{n[0]}</b> {n[1]}<span>{n[2]}</span></div><button className="tiny">View</button></div>)}</div></div>}
function Settings({onLogout}){const [toggles,setToggles]=useState({views:false,likes:false,comments:false,private:false,saving:false});const toggle=k=>setToggles({...toggles,[k]:!toggles[k]});return <div className="page settings"><div className="page-head"><div><p className="eyebrow">ACCOUNT</p><h1>Settings</h1></div></div>{[['statistics','Statistics Settings'],['privacy','Privacy Settings'],['account','Account']].map(([key,title])=><section className="setting-section" key={key}><h3>{title}</h3>{key==='statistics'&&['Hide the number of views','Hide the number of likes','Hide the number of comments'].map((x,i)=>{const k=['views','likes','comments'][i];return <ToggleRow key={k} title={x} sub="Control how engagement counts appear on your posts." on={toggles[k]} toggle={()=>toggle(k)}/>})}{key==='privacy'&&['Hide post from everyone','Disable saving to favorites','Disable comments'].map((x,i)=>{const k=['private','saving','comments'][i];return <ToggleRow key={k} title={x} sub="Change this setting anytime." on={toggles[k]} toggle={()=>toggle(k)}/>})}{key==='account'&&<><button className="setting-link">Edit profile</button><button className="setting-link">Select region</button><button className="setting-link danger" onClick={onLogout}>Log out</button></>}</section>)}</div>}
function ToggleRow({title,sub,on,toggle}){return <div className="toggle-row"><div><b>{title}</b><span>{sub}</span></div><button className={'toggle '+(on?'on':'')} onClick={toggle}><i/></button></div>}
function timeAgo(t){const m=Math.floor((Date.now()-t)/60000);if(m<1)return'now';if(m<60)return m+'m';const h=Math.floor(m/60);if(h<24)return h+'h';return Math.floor(h/24)+'d'}
function App(){const [user,setUser]=useState(null),[page,setPage]=useState('home');useEffect(()=>{const u=auth.currentUser;if(u)setUser(u);const unsub=auth.onAuthStateChanged?.(x=>x&&setUser(x));return ()=>unsub?.()},[]);if(!user)return <Auth onAuth={setUser}/>;const logout=async()=>{try{await signOut(auth)}catch{}setUser(null)};let content=page==='home'?<Home setPage={setPage}/>:page==='explore'?<Explore/>:page==='lines'?<Lines/>:page==='messages'?<Messages setPage={setPage}/>:page==='profile'?<Profile user={user}/>:page==='notifications'?<Notifications/>:<Settings onLogout={logout}/>;return <Shell page={page} setPage={setPage} user={user} onLogout={logout}>{content}</Shell>}

createRoot(document.getElementById('root')).render(<App/>);
